# fly.toml app configuration file generated for santamitsu on 2023-11-06T19:26:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-builder-frosty-snow-9789"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[processes]
  worker = "go run main.go"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false  # prevent automatic suspension
  min_machines_running = 1  # keep a machine running at all times
  processes = ["worker"]

[mounts]
  source="machine_data"  # mount the current directory
  destination="/app"  # to the /app directory in the VM
  process="worker"  # only for the worker process
